# Generated by Django 6.0.1 on 2026-09-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('used', 'Used')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('used', 'Used')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='ticket_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
